#!/bin/bash
puppet resource package git ensure=present
puppet resource package apache2 ensure=present
puppet resource service apache2 ensure=runnning
puppet resource file /testdir/clone ensure=absent force=true
puppet resource file /testdir ensure=directory
puppet resource file /testdir/cline ensure=directory
cd /testdir/clone
git clone https://github.com/BxbyAly97/devops_repo.git
cp -p /testdir/clone/devops_repo/index.html /var/www/html
